# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 665611013a54fad5b3f8b15bbf38ad16ea3b75062315d0e554493e93b5d773d9e5fc1a4caf9927dc5f9085f62a0ea947cfcbf2082c3b2f0a4d170732aa6c4d02

test:
  secret_key_base: f47b385937b22b01b86338412c8c0b675c90c8a195f80fb35bb2007f7b09df9c828cb7f4b0d33dfe44decbc12c006358aebd9a0226d426e6063050804edcd3f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
